apiVersion: csye7125.tutorial.kubebuilder.io/v1
kind: GitHubReleasesMonitor 
metadata: 
  name: cve-githubreleasesmonitor 
  namespace: operator 
spec: 
  url: "https://github.com/CVEProject/cvelistV5/releases" 
  monitorFrom: "2024-07-25"